### ISSUE TITLE
Error when starting connection to ST-Link on S110

### ISSUE THREAD

**Issue by jbehrens94** [dobots/bluenet#13]
When running ./flash_openocd.sh init from ~/bluenet/scripts I receive this error:

ubuntu@ubuntu:~/bluenet/scripts$ ./flash_openocd.sh init
Open On-Chip Debugger 0.9.0-dev-00258-gd537cfa (2015-01-30-16:27)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.sourceforge.net/doc/doxygen/bugs.html
User : 13 4 command.c:546 command_print(): debug_level: 3
Debug: 14 4 options.c:98 add_default_dirs(): bindir=/usr/local/bin
Debug: 15 4 options.c:99 add_default_dirs(): pkgdatadir=/usr/local/share/openocd
Debug: 16 4 options.c:100 add_default_dirs(): run_prefix=
Debug: 17 4 configuration.c:44 add_script_search_dir(): adding /home/ubuntu/.openocd
Debug: 18 4 configuration.c:44 add_script_search_dir(): adding /usr/local/share/openocd/site
Debug: 19 4 configuration.c:44 add_script_search_dir(): adding /usr/local/share/openocd/scripts
Debug: 20 4 configuration.c:84 find_file(): found /home/ubuntu/bluenet/scripts/openocd/openocd.cfg
Debug: 21 5 configuration.c:84 find_file(): found /usr/local/share/openocd/scripts/interface/stlink-v2.cfg
Debug: 22 12 command.c:145 script_debug(): command - ocd_command ocd_command type ocd_interface hla
Debug: 23 13 command.c:145 script_debug(): command - interface ocd_interface hla
Debug: 25 13 command.c:366 register_command_handler(): registering 'ocd_hla_device_desc'...
Debug: 26 13 command.c:366 register_command_handler(): registering 'ocd_hla_serial'...
Debug: 27 13 command.c:366 register_command_handler(): registering 'ocd_hla_layout'...
Debug: 28 13 command.c:366 register_command_handler(): registering 'ocd_hla_vid_pid'...
Debug: 29 13 command.c:366 register_command_handler(): registering 'ocd_trace'...
Debug: 30 13 command.c:366 register_command_handler(): registering 'ocd_hla_command'...
Debug: 31 13 command.c:145 script_debug(): command - ocd_command ocd_command type ocd_hla_layout stlink
Debug: 32 13 command.c:145 script_debug(): command - hla_layout ocd_hla_layout stlink
Debug: 34 13 hla_interface.c:222 hl_interface_handle_layout_command(): hl_interface_handle_layout_command
Debug: 35 13 command.c:145 script_debug(): command - ocd_command ocd_command type ocd_hla_device_desc ST-LINK/V2
Debug: 36 13 command.c:145 script_debug(): command - hla_device_desc ocd_hla_device_desc ST-LINK/V2
Debug: 38 13 hla_interface.c:196 hl_interface_handle_device_desc_command(): hl_interface_handle_device_desc_command
Debug: 39 13 command.c:145 script_debug(): command - ocd_command ocd_command type ocd_hla_vid_pid 0x0483 0x3748
Debug: 40 13 command.c:145 script_debug(): command - hla_vid_pid ocd_hla_vid_pid 0x0483 0x3748
Debug: 42 13 hla_interface.c:250 hl_interface_handle_vid_pid_command(): hl_interface_handle_vid_pid_command
Debug: 43 13 command.c:145 script_debug(): command - ocd_command ocd_command type ocd_debug_level 2
Debug: 44 13 command.c:145 script_debug(): command - debug_level ocd_debug_level 2
debug_level: 2
adapter_nsrst_delay: 100
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 1000 kHz
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : clock speed 950 kHz
Info : STLINK v2 JTAG v14 API v2 SWIM v0 VID 0x0483 PID 0x3748
Info : using stlink api v2
Info : Target voltage: 2.913064
Warn : UNEXPECTED idcode: 0x2ba01477
Error: expected 1 of 1: 0x0bb11477
in procedure 'init' 
in procedure 'ocd_bouncer' 
in procedure 'transport'
in procedure 'init'

**Comment by mrquincle** [comment]
This is very likely because you didn't remove the jumper. See a lot of the blogs of the STM32F board where they use the ST-link for more information as well: https://www.google.nl/search?q=stm32f4&source=lnms&tbm=isch

**Comment by jbehrens94** [comment]
Which jumper should be removed from the STLink board, precisely?

**Comment by mrquincle** [comment]
They are labeled ST-LINK / DISCOVERY. I put it in the manual at https://docs.google.com/a/dobots.nl/document/d/1W-UfzLD4jOh_F5iSbDKcMxwTOVEVfT2QVTTjQlZCXrc as well now.

**Comment by jbehrens94** [comment]
We have removed the jumper from ST-Link and DISCOVERY, now we are receiving:
error: init mode failed (unable to connect to target).

All cables are attached like the manual says, do you have any idea where this error may come from?

**Comment by mrquincle** [comment]
@jbehrens94 I can think of around 5 different ways where this error might come from. Please, help us in filing a new question with the full log, and preferably with a picture of your setup. In that way you do not only help us to pinpoint you problem much quicker, but your question will also become more useful to others. Note that your fellow students have working crownstone boards, so it is extremely likely that you deviated somewhere.

**Comment by ArnoldPMolenaar** [comment]
![Image of setup](http://student.cmi.hr.nl/0882275/jaar2/IMG_1444.JPG)
When I'm at this step I get the following error:

Step:
Start the connection to the ST-Link:
./flash_openocd.sh init

error:
debug_level: 2
adapter_nsrst_delay: 100
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 1000 kHz
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : clock speed 950 kHz
Info : STLINK v2 JTAG v14 API v2 SWIM v0 VID 0x0483 PID 0x3748
Info : using stlink api v2
Info : Target voltage: 2.896161
Error: init mode failed (unable to connect to the target)
in procedure 'init' 
in procedure 'ocd_bouncer' 
in procedure 'transport'
in procedure 'init'

**Comment by ArnoldPMolenaar** [comment]
N.B. COM led is blinking red for a couple of seconds,
