### ISSUE TITLE
ADC structure

### ISSUE THREAD

**Issue by mrquincle** [dobots/bluenet#14]
The buffer that is filled in ADC is misused to also add a timestamp and other data to the current samples.

+ This is just plain ugly. Should be done in a proper structure with those fields if they are necessary.
+ It currently causes a bug. The average current consumption use `voltage_max` which just picks the maximum values from this buffer. It seems the first and last are excluded, but isn't the second also not some kind of timestamp?

**Comment by vliedel** [comment]
This buffer is now completely different, see: https://docs.google.com/a/almende.org/document/d/1W-UfzLD4jOh_F5iSbDKcMxwTOVEVfT2QVTTjQlZCXrc/edit#heading=h.420dq2dugvug
