### ISSUE TITLE
What's the range of a crownstone?

### ISSUE THREAD

**Issue by mrquincle** [dobots/bluenet#15]
I often get the question, what's the actual range of a BLE device such as a crownstone? What is it? :-)

**Comment by vliedel** [comment]
That depends so much on the environment and I think also on the device you use to connect to it. I'm usually able to connect to a crownstone that's attached to the ceiling, 2 floors below me.

**Comment by mrquincle** [comment]
The following shows received data over a course of half an hour, where red is a node on my desk (on the second floor), blue and green are nodes on the same floor, and purple is a node on the ground floor.

![result](https://cloud.githubusercontent.com/assets/1428585/6636673/a334570e-c972-11e4-9cb3-e66871472c03.jpg)

**Comment by rebp** [comment]
Hi, i have a few questions about the crownstone. Is it possible to dim lights whit it, is it possible to manipulate the thermostat for the central heating and what if i have an electric curtain in my house, can I also manipulate it trough the crownstone?
