### ISSUE TITLE
Crownstone 

### ISSUE THREAD

**Issue by rebp** [dobots/bluenet#17]
Hi, i have a few questions about the crownstone. Is it possible to dim lights whit it, is it possible to manipulate the thermostat for the central heating and what if i have an electric curtain in my house, can I also manipulate it trough the crownstone?

**Comment by mrquincle** [comment]
Hi.

* Lights. The current version runs on AC. It can cope with 230V in Europe, and 110V in the US. So, office lights on DC are not yet part of the picture. Dimming we have implemented through PWM (pulse width modulation). 
* An electric curtain. That depends. I think most manufacturers came up with some dedicated way to open or close the curtain (separate box with arrows). I think you will be able to find a nice solution by searching for "motorized curtain" and "smartphone".
* Central heating. This is not likely. If everything goes well we will start to integrate it with central heating systems, but that would require a hub as additional hardware. This will all become much easier when thermostat builders will provide open interfaces to your smartphone. Then integration becomes simple.

The crownstone is meant as a very first, quite basic, actuation possibility. It is able:
* to turn on/off devices
* to be controlled from a smartphone
* to recognize devices that are connected
* to see if people are in a room by registering usage activity (lamps, laptops)
* to track BLE smartphones
* to track BLE peripherals (bracelets etc.)

I think with the latter functionality it is already quite capable. This is the first version coming out. What the future brings... Who knows? :-)
