### ISSUE TITLE
Best way to get to the crownstone data

### ISSUE THREAD

**Issue by Knikker** [dobots/bluenet#18]
Can we get the crownstone to a webpage?

**Comment by vliedel** [comment]
Right now we gather the data via our laptop, see https://github.com/dobots/ble-automator

**Comment by mrquincle** [comment]
There are currently three ways in which you can get the data from the crownstone online:

1. Use something like https://github.com/dobots/ble-automator on a Linux/MacOS laptop and send it over the link with which your laptop is connected to the internet.
2. Use the app https://github.com/dobots/crownstone-app and send it over the link with which your phone is connected.
3. Use the UART / Serial direction directly on the crownstone. This requires you to write the data you want to UART and is the most complicated option (very likely not necessary).
