### ISSUE TITLE
Smart wearables + The Crownstone

### ISSUE THREAD

**Issue by mjanssen** [dobots/bluenet#19]
Has there already been some research for a smart wearable (like Fitbit)? We want to use the wearable as a personal "tracker" in hotels. So it must be connected to a visitors mobile phone.

Our question is, which smart wearable / smart band will work seamlessly with the Crownstone and has the functionality to connect to a mobile phone?

**Comment by mrquincle** [comment]
Those are two questions:

1.) Can you use the crownstone to search for FitBits? Yes. Use the Indoor Localization service with the S130 softdevice.

2.) Can you connect the FitBit to a mobile phone? Yes. If you want to access to the data however, you will need to reverse engineer it. On https://github.com/mrquincle/fitbit-fatbat I have some scripts to connect to a FitBit from a normal laptop. Steps can be retrieved, but not the GPS for example.

I assume you actually do not need the data from the FitBit, just its RSSI values. In that case it will work fine. You can also use a random iBeacon. As long as it advertises it will be fine.

**Comment by mjanssen** [comment]
Thanks for your reply @mrquincle 

Which FitBit do you recommend using in combination with a cellphone and the Crownstone? Several can be found online with completely different prices.

Besides acquiring the right FitBit, is localisation possible while having it connected to your cellphone?

**Comment by mrquincle** [comment]
You're not very clear with your scenario. There doesn't seem to be a reason to use a FitBit. You can use any available iBeacon.

**Comment by mjanssen** [comment]
@mrquincle, we're working on a hotel concept where localisation is a function in our concept. Every visitor is handed a smart wearable (fitbit, smartwatch i.e.) and should be used with the visitors smartphone for personalization. iBeacons would in theory, but are not functional in this concept, because the visitor should wear it like current hotel wristbands. This is why we are searching for a alternative like smartbands.

**Comment by mrquincle** [comment]
You can basically use anything that uses BLE for communication. If you have it connected to your cellphone it does not advertise anymore. In that case you will not be able to find it after a user has connected the device to his/her phone. If you have a list of BLE devices you can run it by me to see if you're not by accident buying something incompatible, but I would be surprised.
