### ISSUE TITLE
Error: softdevice.hex does not exist.

### ISSUE THREAD

**Issue by Boneshock** [dobots/bluenet#22]
Going through step 2.5.2 of the manual;
./softdevice.sh build
returns an error.

"There is no real building step. Nordic provides a binary blob as SoftDevice
However, we still need to extract the binary and the config blob
  from /opt/softdevices/s110_nrf51822_7.0.0
Error: /opt/softdevices/s110_nrf51822_7.0.0_softdevice.hex does not exist..."

**Comment by vliedel** [comment]
Did you check if the file is there? You need to download the files as described in 2.2

**Comment by Boneshock** [comment]
Yes I have download them and completed the steps in 2.2 without errors

**Comment by mrquincle** [comment]
If you download them to the right directory, you will see the mentioned file:

`ls /opt/softdevices | grep s110`

**Comment by vliedel** [comment]
I'll assume this is resolved now.
