### ISSUE TITLE
Unable to match requested speed 1000 kHz, using 950 kHz

### ISSUE THREAD

**Issue by jaapdicker** [dobots/bluenet#24]
When i'm trying to connect to the ST-link during step 2.5.2 using the command ./flash_openocd.sh init, i keep getting the line: Error: open failed, also the lines with Info: Unable to match requested speed 1000 kHz, using 950 kHz. (see foto below)

![image](https://cloud.githubusercontent.com/assets/2848356/7388065/a0ab22a0-ee62-11e4-8abe-b51fab0aaf57.png)

I got this error once before and one of you solved it by replugging some cables, i tried it my self multiple times but i keep getting this error. The manual states that i should get te following line if things are good: Info: nrf51.cpu: hardware has 4 breakpoints, 2 watchpoints.

What can i do to solve it?

thanks in advance.

regards,

**Comment by mrquincle** [comment]
The different speed is not a problem. The not being able to open is a problem however. Make sure you have "rubbed clean" the connector pads of the crownstone with a piece of cloth.

**Comment by vliedel** [comment]
I'll assume this is resolved now.
