### ISSUE TITLE
Init mode failed (unable to connect to the target)

### ISSUE THREAD

**Issue by ArnoldPMolenaar** [dobots/bluenet#25]
![Image of setup](http://student.cmi.hr.nl/0882275/jaar2/IMG_1444.JPG)
An weird error occurred when trying to flash the crownstone by using the TP-Link.

Step:
Start the connection to the ST-Link:
./flash_openocd.sh init

error:
debug_level: 2
adapter_nsrst_delay: 100
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 1000 kHz
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : clock speed 950 kHz
Info : STLINK v2 JTAG v14 API v2 SWIM v0 VID 0x0483 PID 0x3748
Info : using stlink api v2
Info : Target voltage: 2.896161
Error: init mode failed (unable to connect to the target)
in procedure 'init' 
in procedure 'ocd_bouncer' 
in procedure 'transport'
in procedure 'init'

Command lsusb is showing TP-Link device. Jumpers are removed. COM led is blinking for a couple of seconds and after a while turned off.

**Comment by vliedel** [comment]
I see you still have the 2 jumpers connected on the programmer board, they should be taken away.

**Comment by Pindagus** [comment]
I'm having the exact same error, without the two jumpers with label ST-LINK / DISCOVERY.

**Comment by vliedel** [comment]
Pindagus did you make sure the flat cable is connected with the red side inwards? (As shown on the pictures of 2.5.1 of the manual)

**Comment by Pindagus** [comment]
I just found there was one defective wire. I replaced it and all is working well now.

**Comment by mrquincle** [comment]
@Pindagus Nice that you are reporting back! Have fun programming. :+1:
