### ISSUE TITLE
What is the normal operational- and the max. temperature of the Crownstone? 

### ISSUE THREAD

**Issue by nick3085** [dobots/bluenet#26]

**Comment by marciwi** [comment]
Typically the crownstone should be between -25 and 75 degrees Celcius. Normally this should average at about 25 degrees, but we've run it reliably at temperatures up to 60 degrees.

**Comment by nick3085** [comment]
When I connect the Crownstone to 230v it has a temp of 65*C, could that be a problem?

**Comment by marciwi** [comment]
65 degrees should be fine.
