### ISSUE TITLE
'replace ttyUSB0 with the correct device'

### ISSUE THREAD

**Issue by jbehrens94** [dobots/bluenet#27]
On my ubuntu live USB, there is no /dev/ttyUSB0, but how do I figure out which device is the right one?

**Comment by jbehrens94** [comment]
And should we set bootloader=true on s130? That is not clear to us from the manual.

**Comment by vliedel** [comment]
Hi Johann, please ask separate questions in separate issues.

The ttyUSB0 is created when you plug in a USB serial device, like the rfduino usb shield. It can have a different number though, check with: `ls /dev/ttyUSB*`

Adding the bootloader is optional, you will need it to program over the air.

**Comment by mrquincle** [comment]
Use `lsusb` before and after you plug in a device. Then check `cat /var/log/syslog`.

**Comment by vliedel** [comment]
I'll assume this is resolved now.
