### ISSUE TITLE
Flashing Crownstone as iBeacon Stuck 

### ISSUE THREAD

**Issue by nick3085** [dobots/bluenet#29]
See underneath, I takes really long to flash the crownstone. 
last night it took 1,5 hour, after that time I stopped the connection. 
Now I have a problem after 20 min it sais:

Today:

wrote 146432 bytes from file /home/ubuntu/crownstone/build/combined.hex in 406.442566s (0.352 KiB/s)
Info : dropped 'telnet' connection

Last Night: 

#ubuntu@ubuntu:~/bluenet/scripts$ ./flash_openocd.sh combined
spawn telnet 127.0.0.1 4444
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Open On-Chip Debugger
> halt
> flash banks
#0 : nrf51.flash (nrf51) at 0x00000000, size 0x00000000, buswidth 1, chipwidth 1
#1 : nrf51.uicr (nrf51) at 0x10001000, size 0x00000000, buswidth 1, chipwidth 1
> echo We will do a mass-erase
in procedure 'echo'
> nrf51 mass_erase
nRF51822-QFAA(build code: CA/C0) 256kB Flash
> flash write_image erase /home/ubuntu/crownstone/build/combined.hex 0
auto erase enabled
Padding image section 0 with 2112 bytes
Padding image section 1 with 3420 bytes

**Comment by vliedel** [comment]
This shouldn't take 1.5 hours, are you using a VM by any chance?

**Comment by nick3085** [comment]
Using Parallels on a mac retina

**Comment by vliedel** [comment]
Then that VM makes the connection to the ST-Link very slow, I've seen that before. You'll have to try some other way to run it then.

**Comment by nick3085** [comment]
is it possible for us to drop by and get some support? 

Kind regards, 

Nick de Ronde 
nick@nickderonde.nl

**Comment by vliedel** [comment]
Sure, just send us an email to make an appointment.

**Comment by vliedel** [comment]
But don't expect us to fix VM software ;)

**Comment by nick3085** [comment]
Which email could I send it? You don't have to fix the VM software^^

**Comment by mrquincle** [comment]
Je kan ons allemaal (https://dobots.nl/about-us/) bereiken via voornaam en dan gewoon @dobots.nl erachter aan te plakken. In dit geval heb je bart nodig. :-)
