### ISSUE TITLE
CHAR_MESHING? 

### ISSUE THREAD

**Issue by nick3085** [dobots/bluenet#30]
Could any one explain something about CHAR_MESHING? 

I found something about it in this link: 
https://github.com/NordicSemiconductor/nRF51-ble-bcast-mesh/blob/master/docs/how_it_works.adoc
But it's like gibberish for me :(

- What is it? 
- What can I do with it or without it?

**Comment by vliedel** [comment]
Hi nick, this is a setting to enable meshing (crownstones talking to each other without connecting via bluetooth). This is currently under development, so not stable yet. You would have to use the meshing branch.

**Comment by nick3085** [comment]
Coowl Thnx for the info
