### ISSUE TITLE
CMake problem

### ISSUE THREAD

**Issue by jeroentuk** [dobots/bluenet#31]
Hi,

We're experiencing some problems while running `./firmware.sh build crownstone` from your documentation.

The error we're receiving is: 

Missing variable is:
CMAKE_CXX_COMPILER_ENV_VAR
CMake Error: Could not find cmake module file: /home/ubuntu/bluenet/build/CMakeFiles/2.8.12.2/CMakeCompiler.cmake

Is there any way to resolve this problem?

**Comment by chaasfr** [comment]
Hello,

It looks like there is something wrong with your g++ or cmake. Do you have the same issue with other projects? Try to install or reinstall g++ and cmake, clear cmake cache and build the firmware:

`sudo apt-get update`
`sudo apt-get install g++ cmake ` (you may need to add a --reinstall option)
`rm /home/ubuntu/bluenet/build/CMakeCache.txt`
`cd /home/ubuntu/bluenet/scripts`
`./firmware.sh build crownstone`

**Comment by mrquincle** [comment]
You need a cross-compiler, follow the tutorial from the README. And post the results of:

```
cmake --version
grep -r CMAKE_CXX_COMPILER_ENV_VAR .
grep -r "set(CMAKE_CXX_COMPILER " .
```

And check if the file that is the result of the last grep actually exist.

Also, remove the `build` directory to build again from scratch.

**Comment by eggerdo** [comment]
no reponse for 3 weeks, assume this is solved?
