### ISSUE TITLE
UUID for Crownstone

### ISSUE THREAD

**Issue by jbehrens94** [dobots/bluenet#32]
When working with live crownstones, what is the best way to gather the UUIDs to work with?
Do we need to know the UUIDs on forehand, or are we able to gather them programmatically?

**Comment by vliedel** [comment]
Which UUIDs do you  mean? UUIDs of services and characteristics or ibeacon
UUID?

**Comment by jbehrens94** [comment]
I'll try to specify: I'm working on our iOS app, and the `CLBeaconRegion` expects a `proximityUUID`.
According to this [post](http://willd.me/posts/getting-started-with-ibeacon-a-swift-tutorial): 'To define a region, you'll need to know the UUID of the beacons you are using.'

So I assume I need to know the UUID used for crownstones, is there a fixed one? Or will I be able to use all the crownstones at Hogeschool Rotterdam, with one UUID?

**Comment by vliedel** [comment]
This looks like the ibeacon UUID you're talking about. To program your crownstone such that it conforms the ibeacon protocol, set IBEACON=1 and then you'll find that BEACON_UUID can be set.

**Comment by jbehrens94** [comment]
Where should I set those two variables? In CMakeBuild.config, or later on in the process?

**Comment by vliedel** [comment]
They should be in the CMakeBuild.config. See the [default](https://github.com/dobots/bluenet/blob/master/CMakeBuild.config.default).

**Comment by jbehrens94** [comment]
Can I safely assume the crownstones at Hogeschool Rotterdam will not have a general UUID per crownstone? What is the best way to use their abilities during the Sprint Review?

**Comment by eggerdo** [comment]
if you have an android phone you can download the DoBeacon App at https://play.google.com/store/apps/details?id=nl.dobots.dobeacon and use it to change UUID, major and minor without having to reprogram them

**Comment by jbehrens94** [comment]
My OS X BeaconScanner is not able to find the crownstone, reporting that the proximityUUID is a string ("null"). Is that UUID to be set manually, or should that be set by default?
For iOS, I need to be able to find the proximityUUID of crownstones, which is prohibited in CoreBluetooth's API. On OS X it is meant to work perfectly fine, but it does not find the crownstone.

So, do I need to manually set the proximityUUID, or is there a default?

**Comment by mrquincle** [comment]
Did you try the apps from dartle.io?

**Comment by eggerdo** [comment]
There is no default for the proximity UUID, it is specified per application. If you don't get it to work on OSX with the UUID that is currently configured, which is as I mentioned earlier 00000000-0000-0000-0000-000000000000, then you can reconfigure them with a new UUID. Use a UUID generator, e.g. https://www.uuidgenerator.net/, then use the dobeacon app on an android phone / tablet to update the UUIDs of the beacons (all beacons with the same UUID). But if you change the UUID's make sure your colleagues are aware of that change!!

**Comment by jbehrens94** [comment]
Alright, we are able to find all of the beacons in the classroom, unfortunately I am receiving 0 for all beacons' RSSI value.
Other apps do this perfectly fine, so the RSSI can only be < 0 dB if you are within the 1 meter range?

**Comment by eggerdo** [comment]
Are you referring to the RSSI value that is measured while scanning and changes based on the distance to the beacon, or the RSSI value which is in the beacon's advertisement message?

**Comment by jbehrens94** [comment]
In my source code, I am ranging the beacons based on the common proximityUUID. Then I collect the RSSI from that beacon, so I assume I am collecting the RSSI Value used while scanning?
In the CoreBluetooth API from Apple, I am finding an array of beacons with their RSSI and other values.

I'm not sure how aware you are with that SDK?

**Comment by eggerdo** [comment]
I'm afraid I don't have any experience programming on iOS so I cannot tell for sure which RSSI value that is. Can you pinpoint me to the API Docs of the function you are using, probably that should explain which one it is. 
Also you said other apps do this perfectly fine, so if you use another iBeacon scanner it does report back correct RSSI values and is able to calculate a distance measurement?

**Comment by jbehrens94** [comment]
This is the object iOS returns for every beacon it finds. https://developer.apple.com/library/prerelease/ios/documentation/CoreLocation/Reference/CLBeacon_class/index.html#//apple_ref/swift/cl/c:objc(cs)CLBeacon

**Comment by eggerdo** [comment]
OK, yes according to the docs that should be the current RSSI value, or better 'the average RSSI value of the samples received since the range of the beacon was last reported to your app.' So that should definitely not be 0. I also don't think this is the fault of the beacons, but rather some problem on the phone. You don't by chance have any other iBeacons (not DoBeacons) you can test it with?

Some other things to try, 
- is the value always 0 no matter how close or far away you are from the beacon?
- does this happen with all the beacons that are installed?
- what do you get in the proximity property? does that change depending on your distance from the beacon?

Other than that, I suggest you google for any issues regarding iOS, iBeacon and received RSSI values always 0, maybe something pops up.

**Comment by jbehrens94** [comment]
The value is always 0, when I move or sit still with the iPhone or iPad (I have tested this with both devices). This happens with all the installed Beacons at Hogeschool Rotterdam, and the proximity property always logs `+/- –1m` with `RSSI 0`.

I'll try to search for more information, thank you very much for your intensive help.

**Comment by jbehrens94** [comment]
Can I also request the RSSI via the `General Service` UUIDs? Is that the value generated every 100ms?

**Comment by eggerdo** [comment]
The RSSI Characteristic is part of the Indoor Localization Service and not enabled on the DoBeacons.

Does that mean you still get RSSI values of 0 on iOS? There seem to be some problems in general with [CoreLocation](http://developer.radiusnetworks.com/2013/10/21/corebluetooth-doesnt-let-you-see-ibeacons.html), or [iOS 8](http://stackoverflow.com/questions/24062509/location-services-not-working-in-ios-8). Might be you have a similar issue?

**Comment by jbehrens94** [comment]
That is true, but according to the SDK documentation on Google Docs, there is a "get configuration" service on the general service. And on the next page, I can tell there is a setting `CONFIG_IBEACON_RSSI`, but that would be a fixed one, as far as I can tell?

And I am aware that there are some problems with iOS, I have been able to solve most of them, by using the proximityUUID as stated in this or the other issue on bluenet. I can register all of the DoBeacons, but just not their RSSI, which is pretty vital, I would say.

**Comment by eggerdo** [comment]
Ah I see, the `CONFIG_IBEACON_RSSI` is the calibrated RSSI value at 1m, so the fixed value. We are using this to configure the beacons without having to reprogram them. It is not the measured RSSI value.

**Comment by jbehrens94** [comment]
Loud and clear, thank you! I think both of the issues can be closed now, due to the iOS/CoreBluetooth API being the cause of my bugs.
Thank you very much for helping!
