### ISSUE TITLE
How To flash without date?

### ISSUE THREAD

**Issue by nick3085** [dobots/bluenet#33]
How can I flash the Crownstone without date or change the name easy?

**Comment by eggerdo** [comment]
Fastest way right now is to replace line 162 in cs_main_crownstone.cpp with

```
sprintf(devicename, "%s", STRINGIFY(BLUETOOTH_NAME));
```

It is possible to set it with a configuration characteristic as well but that would take some more time to explain. We are updating the app on the google play store which will be able to change the name while the crownstone is running.

**Comment by eggerdo** [comment]
Both apps on the market are now updated and can change the names at run time. To configure Crownstones, use the [crownstone-app](https://play.google.com/store/apps/details?id=nl.dobots.CrownStone), to configure DoBeacons use the [dobeacon-app](https://play.google.com/store/apps/details?id=nl.dobots.dobeacon)
