### ISSUE TITLE
Crownstones at Hogeschool Rotterdam

### ISSUE THREAD

**Issue by jbehrens94** [dobots/bluenet#34]
I am at Hogeschool Rotterdam at this moment, trying to work on location services on the crownstones. As far as I can see, when I connect to a crownstone, the implemented services are only the `F5F9000x` services, not the locational services as described in the Crownstone Readme.
Are we able to use the location services from the DoBeacon_1/2/3/4?

**Comment by mrquincle** [comment]
What's the result of

```
cat CMakeBuild.config | grep SERVICE
```

**Comment by jbehrens94** [comment]
How can I run that command at Hogeschool Rotterdam? I don't have the DoBeacons connected to my MacBook or something.
The iOS BLE Utility only shows the F5F9 service, no 7E17 service.

**Comment by mrquincle** [comment]
Running commands you do in the terminal.

You can to program it if you forgot to enable services while uploading the firmware.

**Comment by jbehrens94** [comment]
I am not talking about my own crownstone, but about the installed beacons in the classroom, which I can't access from Ubuntu or whatever.

**Comment by mrquincle** [comment]
Okay. @vliedel should know. If they are DoBeacons, they should only advertise beacon messages. No other services.

**Comment by jbehrens94** [comment]
We received an email from Emiel, saying the beacons should be used to perform location services, so this is definitely not possible?

**Comment by eggerdo** [comment]
Yes that is correct, the installed beacons only have the General Service (chapter 1.2 in the SDK) enabled. Indoor Localization Service is not available. What do you want to do exactly? The idea with the beacons is that you use the phone to localize using the information in the advertisement package of the beacons.

**Comment by jbehrens94** [comment]
Don't we need Indoor Localization Services to be able to present our work to you?

**Comment by eggerdo** [comment]
The Indoor Localization Service as it is now in the bluenet code only provides the following two functions:
- Scan for and report a list of scanned devices
- Track a list of devices and turn on a lamp if one of the tracked devices comes close, and turn off a lamp once no tracked device has been seen within a certain distance for a given time.

The latter does not make sense for the beacons as they don't have the capability to switch on/off devices.

If you want to do indoor localization on the crownstones you will need to write/improve code in the bluenet and use your own crownstones for that. They can also be configured to advertise themselves as iBeacons of that is a further requirement.

The beacons that are installed can  in their present state only be used to do indoor localization on the phone.

So it really depends on your task/objective if you need the Indoor Localization Service or not.

**Comment by jbehrens94** [comment]
So the General Service localization is supposed to be based on the RSSI service? If I understand correctly?

**Comment by eggerdo** [comment]
The installed beacons advertise an rssi value, which is the calibrated signal strength at 1 meter distance from the beacon. Use that and your current rssi value that you get when scanning with the phone for devices to calculate your distance from the beacon. do that for another 2 beacons and you can triangulate your position.

**Comment by vliedel** [comment]
Of course, these values are rather noisy, but with a simple algorithm, you should at least be able to tell which of the beacons is closest. You probably want this algorithm to run on your phone, not on the crownstones or beacons.

**Comment by jbehrens94** [comment]
I suppose that using the RSSI at ≤ 1 meter will not give us the ability to really triangulate well, or am I wrong on this?
I imagine if the RSSI is up to 1 meter, we can't really determine which one is the closest, if standing in the middle of the room, with the beacons places in the corners?

**Comment by wouterbulten** [comment]
You can use the RSSI at 1 meter as an input in the path loss model which can translate RSSI to distance (in meters):

RSSI (dBm) = -10n log10(d) + A

Where 'A' is the RSSI at 1m, 'd' the distance in meters and 'n' a constant based on the environment (which is often set to 2). This distance measure is however very inaccurate (due to the noise in the RSSI signal) so you need to do some filtering.

See for more info http://electronics.stackexchange.com/questions/83354/calculate-distance-from-rssi or google 'rssi to distance' for some more examples :)

**Comment by jbehrens94** [comment]
And I'll have to keep in mind that the RSSI will not be > 1 meter?

**Comment by wouterbulten** [comment]
What do you mean with the 'RSSI will not be > 1 meter'? You can use the path loss model at distances > 1 meter if that is what you mean.
