### ISSUE TITLE
reset always makes it go to dfu mode

### ISSUE THREAD

**Issue by vliedel** [dobots/bluenet#35]
When i reset the crownstone via the reset characteristic (write value "1"), it goes to dfu mode.

**Comment by mrquincle** [comment]
Are you sure you use the newest bootloader? Only a value COMMAND_ENTER_RADIO_BOOTLOADER should result in staying in the bootloader. See https://github.com/dobots/nrf51-dfu-bootloader-for-gcc-compiler/blob/s110/nrf51822_v6.0.0%20-%20GCC_Bootloader/Board/nrf6310/device_firmware_updates/bootloader%20-%20gcc%20-%20BLE/main.c

**Comment by vliedel** [comment]
Ah, turns out I wasn't and the old code still had COMMAND_ENTER_RADIO_BOOTLOADER=1.
